name: CI

on:
  push:
  release:
    types: [published]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Checkout private ci-assets
        uses: actions/checkout@v2
        with:
          repository: dasch-swiss/dsp-ci-assets
          token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: ci
      - name: Copy ci-assets
        run: |
          cp $GITHUB_WORKSPACE/ci/kakadu/v8_0_5-01727L.zip $GITHUB_WORKSPACE/vendor/v8_0_5-01727L.zip
      - name: run compile and tests inside docker
        run: make test-ci
      - name: publish docker image (on release only)
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make publish-sipi-image
      - name: Update release notes
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        uses: lakto/gren-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
